//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredHack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Employers = new HashSet<Employer>();
            this.PayTypes = new HashSet<PayTypes>();
        }
    
        public int JobID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public string BaseSalary { get; set; }
        public int PayTypeID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employer> Employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayTypes> PayTypes { get; set; }
        public virtual JobCCConnection JobCCConnection { get; set; }
        public virtual EmployeeJobConnection EmployeeJobConnection { get; set; }
    }
}
