//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredHack.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WiredHackEntities : DbContext
    {
        public WiredHackEntities()
            : base("name=WiredHackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CareerCluster> CareerClusters { get; set; }
        public virtual DbSet<JobCCConnection> JobCCConnections { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<PayTypes> PayTypes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeJobConnection> EmployeeJobConnections { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<UserEmployeeConnection> UserEmployeeConnections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
    
        public virtual int CreateAccount(string firstName, string lastName, Nullable<int> employerID, string username, string password, string email)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var employerIDParameter = employerID.HasValue ?
                new ObjectParameter("EmployerID", employerID) :
                new ObjectParameter("EmployerID", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAccount", firstNameParameter, lastNameParameter, employerIDParameter, usernameParameter, passwordParameter, emailParameter);
        }
    
        public virtual int PasswordReset(string username, string password, string newPassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PasswordReset", usernameParameter, passwordParameter, newPasswordParameter);
        }
    
        public virtual ObjectResult<UserLogin_Result> UserLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogin_Result>("UserLogin", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetCareerClusterJobChart_Result> GetCareerClusterJobChart(Nullable<int> cCID)
        {
            var cCIDParameter = cCID.HasValue ?
                new ObjectParameter("CCID", cCID) :
                new ObjectParameter("CCID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCareerClusterJobChart_Result>("GetCareerClusterJobChart", cCIDParameter);
        }
    
        public virtual ObjectResult<GetCareerClusterSchoolChart_Result> GetCareerClusterSchoolChart(Nullable<int> cCID)
        {
            var cCIDParameter = cCID.HasValue ?
                new ObjectParameter("CCID", cCID) :
                new ObjectParameter("CCID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCareerClusterSchoolChart_Result>("GetCareerClusterSchoolChart", cCIDParameter);
        }
    
        public virtual ObjectResult<GetCareerClusterEmployees_Result> GetCareerClusterEmployees(Nullable<int> cCID)
        {
            var cCIDParameter = cCID.HasValue ?
                new ObjectParameter("CCID", cCID) :
                new ObjectParameter("CCID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCareerClusterEmployees_Result>("GetCareerClusterEmployees", cCIDParameter);
        }
    }
}
